### ISSUE TITLE
How can I do an inference on a video?

### ISSUE THREAD

**Issue by ZviLvision** [lingan1996/ACTION-NET#2]

**Comment by qinghuannn** [comment]
For the Rhythmic Gymnastics dataset, you can first download the pre-extracted features from [here](https://mail2sysueducn-my.sharepoint.com/:u:/g/personal/zenglan3_mail2_sysu_edu_cn/EZAMHnaNkH9DuMjy_Qa-zuoBYcB2y1xr_R6hK2kGUagBGA?e=7ojkTn) and unzip it to the `./data` directory. Then, run `python main.py --action_type Ball -test`.
For others, you need to use the `extract_static_feat.py` and `extract_static_feat.py` to extract features. Additionally, you could find the details of how to preprocess a video in the [paper](https://arxiv.org/abs/2008.05977).
